openapi: '3.0.2'
info:
  title: Sprint Cup
  version: '1.0'
servers:
  - url: https://api.server.test/v1
tags: 
- name: "Authorization"
  description: "Regitering new users and logging in"
- name: "Profile"
  description: "Personal information such as the users real name"

paths:
  /auth/login:
    post:
      tags: 
      - "Authorization"
      summary: "Login to recieve a JWT token"

      parameters:
        - name: "email"
          description: "The email address used to sign up"
          schema:
            type: string        
          required: true
        - name: "password"
          description: "The password the user used to register"
          schema:
            type: string           
          required: true          

      responses:
        '200':
          description: OK
          headers:
          content:
            application/json:
              schema:
                type: string
        
        '400': 
          description: Incorrect username or password
          headers:
          content:
            application/json:
              schema:
                type: string

        
  /auth/register:
    post:
      tags: 
      - "Authorization"
      summary: "Register a new user"
      parameters:
        - name: "email"
          description: "The email address used to sign up"
          schema:
            type: string        
          required: true
        - name: "password"
          description: "The password the user used to register"
          schema:
            type: string           
          required: true          
          
      responses:
        '200':
          description: OK
        '400':
          description: Email already in use



  /profile/:
    post:
      tags: 
      - "Profile"
      summary: "Login to recieve a JWT token"
      responses:
        '200':
          description: OK