openapi: '3.0.2'
info:
  title: Sprint Cup
  version: '1.0'
servers:
  - url: https://api.server.test/v1
tags: 
- name: "Authorization"
  description: "Regitering new users and logging in"
- name: "Profile"
  description: "Personal information such as the users real name"
paths:
  /auth/login:
    get:
      tags: 
      - "Authorization"
      summary: "Login to recieve a JWT token"
      parameters:
        - name: "email"
          description: "The email address used to sign up"
          required: true
          
      responses:
        '200':
          description: OK


