name: continuous integration # Just a name o fthe workflow

on:
  push:
    branches: [master] # The workflow will be triggered when someone pushes to master.

# Jobs are run in parallel by default
# They can be optionally made to be run in order

jobs:
  test_suite:
    runs-on: ubuntu-latest # The test_suite, runs on the latest ubuntu VM
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2 # This loads up our repo into the VM. ie git clone into the VM.
